name: Publication de l'image Docker sur DockerHub
on:
  workflow_call:
    inputs:
      # Paramètres obligatoires
      docker-repository-name:
        description: "Repository Docker sur lequel publier l'image"
        type: string
      # Paramètres optionnels pour la configuration du runner
      runner-distro:
        default: "ubuntu-latest"
        description: "Distribution linux du runner à utiliser"
        type: string
      java-sdk-version:
        default: "19"
        description: "Version du SDK Java à utiliser"
        type: string
      java-sdk-distro:
        default: "temurin"
        description: "Distribution du SDK Java à utiliser"
        type: string

jobs:
  push_to_registry:
    name: Push de l'image docker sur Docker Hub
    runs-on: ${{ inputs.runner-distro }}

    steps:
      # ------------
      - name: Git checkout
        uses: actions/checkout@v3
      # ------------
      - name: Installation du JDK  ${{ inputs.java-sdk-version }} (${{ inputs.java-sdk-distro }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-sdk-version }}
          distribution: ${{ inputs.java-sdk-distro }}
          cache: maven
      # ------------
      - name: Build avec Maven
        run: mvn -B -U package
      # ------------
      - name: Connexion à Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extraction des metadata (tags, labels) pour Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: medhead/${{ inputs.docker-repository-name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}